### ISSUE TITLE
c1xx : fatal error C1083: 无法打开源文件: “..\..\vcglib\wrap\ply\plylib.cpp”

### ISSUE THREAD

**Issue by sui0312feng** [nxddsnc/gltf-to-3dtiles#10]
i use your meshod to compile this project ,  vs show "c1xx : fatal error C1083: 无法打开源文件: “..\..\vcglib\wrap\ply\plylib.cpp”".

**Comment by sui0312feng** [comment]
be short of “....\vcglib\wrap\ply\plylib.cpp”

**Comment by nxddsnc** [comment]
Plz use the lastest version of vcglib and switch it to branch named 'devel'.
