### ISSUE TITLE
i'm  compile fail, can you give me exe  file ? 

### ISSUE THREAD

**Issue by dmff** [nxddsnc/gltf-to-3dtiles#12]
email 1162661554@qq.com

**Comment by chenzaichun** [comment]
I've created a PR #13 for binary build. you could use files I built: [https://github.com/chenzaichun/gltf-to-3dtiles/releases](https://github.com/chenzaichun/gltf-to-3dtiles/releases)

**Comment by dmff** [comment]
thanks

**Comment by dmff** [comment]
> I've created a PR #13 for binary build. you could use files I built: https://github.com/chenzaichun/gltf-to-3dtiles/releases
thanks
