### ISSUE TITLE
<vcg/complex/algorithms/isotropic_remeshing.h>

### ISSUE THREAD

**Issue by zhouqi999** [nxddsnc/gltf-to-3dtiles#9]
be short of <vcg/complex/algorithms/isotropic_remeshing.h>

**Comment by nxddsnc** [comment]
I think you can solve this by downloading the latest version of vcglib.

**Comment by zhouqi999** [comment]
Could you tell me the download address of the latest version?
Current version：“http://github.com/cnr-isti-vclab/vcglib/”

**Comment by nxddsnc** [comment]
I used the same repo but I switched it to branch named 'devel'.
